2025-07-29 20:00:19,468 INFO    MainThread:139112 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/melih/Documents/Bites_CPU_Analizi/wandb/run-20250729_200019-ychow08h/logs/debug.log
2025-07-29 20:00:19,468 INFO    MainThread:139112 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/melih/Documents/Bites_CPU_Analizi/wandb/run-20250729_200019-ychow08h/logs/debug-internal.log
2025-07-29 20:00:19,468 INFO    MainThread:139112 [wandb_init.py:init():830] calling init triggers
2025-07-29 20:00:19,468 INFO    MainThread:139112 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'model': 'LSTM', 'epochs': 15, 'optimizer': 'Adam', 'loss_function': 'MSELoss', 'learning_rate': 0.001, 'lookback': 10, 'features': ['cpu_usage', 'memory_usage'], '_wandb': {}}
2025-07-29 20:00:20,807 INFO    MainThread:139112 [wandb_init.py:init():871] starting backend
2025-07-29 20:00:20,807 INFO    MainThread:139112 [wandb_init.py:init():874] sending inform_init request
2025-07-29 20:00:20,808 INFO    MainThread:139112 [wandb_init.py:init():882] backend started and connected
2025-07-29 20:00:20,809 INFO    MainThread:139112 [wandb_run.py:_label_probe_notebook():1304] probe notebook
2025-07-29 20:00:20,814 INFO    MainThread:139112 [wandb_init.py:init():953] updated telemetry
2025-07-29 20:00:20,817 INFO    MainThread:139112 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-29 20:00:21,551 INFO    MainThread:139112 [wandb_init.py:init():1029] starting run threads in backend
2025-07-29 20:00:21,599 INFO    MainThread:139112 [wandb_run.py:_console_start():2458] atexit reg
2025-07-29 20:00:21,599 INFO    MainThread:139112 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-29 20:00:21,599 INFO    MainThread:139112 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-29 20:00:21,599 INFO    MainThread:139112 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-29 20:00:21,600 INFO    MainThread:139112 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-29 20:00:23,594 WARNING MsgRouterThr:139112 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 231, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 216, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-29 20:00:23,596 INFO    MsgRouterThr:139112 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
